### ISSUE TITLE
Timetable to the footer

### ISSUE THREAD

**Issue by andreasonny83** [RhythmicExcellence/rhythmicexcellence.london#14]
Put a timetable link to the footer

**Comment by dshubhadeep** [comment]
Hey @andreasonny83 , can I work on this issue ?

**Comment by andreasonny83** [comment]
Sure no problem @dshubhadeep

**Comment by andreasonny83** [comment]
Sorry @dshubhadeep but I just implemented that feature along with some other minor fixes
