### ISSUE TITLE
Timetable text not centered

### ISSUE THREAD

**Issue by andreasonny83** [RhythmicExcellence/rhythmicexcellence.london#7]
Given I'm a mobile user
When I navigate to the timetable page
And I'm in portrait view
Then the page view is bigger than the device screen size

<img width="448" alt="screen shot 2018-10-11 at 20 54 16" src="https://user-images.githubusercontent.com/8806300/46830256-fb9e2000-cd97-11e8-8498-b9c4f5b4afe5.png">

**Comment by weberjacob** [comment]
Came across this from the Hacktoberfest tag. This appears to be happening due to the `.Timetable` grid styling. The title along with the other `.Timetable__day` content are too large for mobile.

**Comment by andreasonny83** [comment]
Can you fix this @weberjacob  ?

**Comment by weberjacob** [comment]
Sure, I'll submit a PR shortly.
